"""
Headless tests for the pure, Tkinter-free helpers added to vault_lib/gui.py
as part of the 1.4.0 recovery-key / v2 vault surface.

Everything here is headless -- no tk.Tk() is created, no display is needed,
and tkinter is not instantiated.  The four module-level pure functions being
exercised are:

  _validate_password_fields(pw, confirm) -> Optional[str]
      Validates a new-password pair; returns an error string or None.

  _parse_rk_input(text) -> (bytearray | None, str | None)
      Checksum-verifies a recovery-key string; returns (raw, None) on success
      or (None, friendly_error) on failure.

  _applicable_manage_actions(info) -> list[str]
      Given a vault_info() dict, returns the list of action IDs that make
      sense for the current vault state.

  _manage_action_result_keys(action) -> frozenset[str]
      Returns the frozenset of dict keys manage_vault_dialog puts in its
      outcome for the given action -- the "contract" for each action.

The test also exercises:
  * The _applicable_manage_actions / _manage_action_result_keys contract
    end-to-end using real vault_info()-shaped dicts.
  * _parse_rk_input with a real recovery key generated by crypto, and with
    intentionally corrupted inputs to verify friendly error messaging.

Call convention: plain `def test_x() -> None:` functions; banners as
75-dash lines with a prose paragraph; standalone runner block prints
`Results: N/N passed`.
"""
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from vault_lib.gui import (
    _validate_password_fields,
    _parse_rk_input,
    _applicable_manage_actions,
    _manage_action_result_keys,
    MIN_PASSWORD_LEN,
)
from vault_lib.crypto import new_recovery_key, format_recovery_key


# ---------------------------------------------------------------------------
# _validate_password_fields
#
# This pure function is the single source of password-validation logic used
# by manage_vault_dialog (change-password action) and recover_dialog.  It
# must reject empty passwords, passwords shorter than MIN_PASSWORD_LEN, and
# mismatched confirmation fields, and must return None for a valid pair.
# ---------------------------------------------------------------------------

def test_validate_empty_password_returns_error() -> None:
    result = _validate_password_fields("", "")
    assert result is not None, (
        "REGRESSION: _validate_password_fields('', '') returned None; "
        "empty password must produce an error string"
    )


def test_validate_empty_password_error_is_string() -> None:
    result = _validate_password_fields("", "anything")
    assert isinstance(result, str) and len(result) > 0, (
        "REGRESSION: _validate_password_fields returned a non-string or empty string "
        "for an empty first password"
    )


def test_validate_short_password_returns_error() -> None:
    short = "x" * (MIN_PASSWORD_LEN - 1)
    result = _validate_password_fields(short, short)
    assert result is not None, (
        f"REGRESSION: _validate_password_fields accepted a {len(short)}-char password; "
        f"must require at least {MIN_PASSWORD_LEN}"
    )


def test_validate_short_password_mentions_length() -> None:
    short = "tooshort1"
    result = _validate_password_fields(short, short) or ""
    assert str(MIN_PASSWORD_LEN) in result, (
        f"REGRESSION: error for short password does not mention {MIN_PASSWORD_LEN}; "
        f"got: {result!r}"
    )


def test_validate_mismatch_returns_error() -> None:
    good = "a" * MIN_PASSWORD_LEN
    result = _validate_password_fields(good, good + "x")
    assert result is not None, (
        "REGRESSION: _validate_password_fields returned None for mismatched "
        "confirmation; mismatch must produce an error"
    )


def test_validate_valid_pair_returns_none() -> None:
    good = "a" * MIN_PASSWORD_LEN
    result = _validate_password_fields(good, good)
    assert result is None, (
        f"REGRESSION: _validate_password_fields({good!r}, {good!r}) returned "
        f"{result!r} instead of None for a valid password pair"
    )


def test_validate_exactly_min_len_is_accepted() -> None:
    pw = "x" * MIN_PASSWORD_LEN
    result = _validate_password_fields(pw, pw)
    assert result is None, (
        f"REGRESSION: exactly {MIN_PASSWORD_LEN}-char password was rejected; "
        f"MIN_PASSWORD_LEN is the minimum, inclusive"
    )


def test_validate_long_password_accepted() -> None:
    pw = "a" * 64
    result = _validate_password_fields(pw, pw)
    assert result is None, (
        "REGRESSION: 64-char password was rejected by _validate_password_fields"
    )


# ---------------------------------------------------------------------------
# _parse_rk_input
#
# Wraps crypto.parse_recovery_key with a friendly error string so the UI can
# say "looks like a typo" rather than surfacing a raw exception.  A valid
# recovery key must parse to a bytearray of the right length; an invalid one
# must return (None, non-empty-string).  Key material in the returned
# bytearray is zeroed in each test.
# ---------------------------------------------------------------------------

def _make_valid_rk():
    """Return a (key_text, raw_bytes) pair for a freshly generated key."""
    raw = new_recovery_key()
    text = format_recovery_key(bytes(raw))
    return text, raw


def test_parse_rk_valid_returns_bytearray() -> None:
    text, raw_orig = _make_valid_rk()
    parsed, err = _parse_rk_input(text)
    try:
        assert err is None, f"REGRESSION: valid key produced error: {err!r}"
        assert isinstance(parsed, bytearray), (
            "REGRESSION: _parse_rk_input did not return a bytearray for a valid key"
        )
    finally:
        if parsed is not None:
            for i in range(len(parsed)):
                parsed[i] = 0
        for i in range(len(raw_orig)):
            raw_orig[i] = 0


def test_parse_rk_valid_bytearray_has_correct_length() -> None:
    text, raw_orig = _make_valid_rk()
    parsed, err = _parse_rk_input(text)
    try:
        assert err is None
        # 20 bytes — crypto.RECOVERY_KEY_BYTES
        assert len(parsed) == 20, (
            f"REGRESSION: parsed recovery key has {len(parsed)} bytes, expected 20"
        )
    finally:
        if parsed is not None:
            for i in range(len(parsed)):
                parsed[i] = 0
        for i in range(len(raw_orig)):
            raw_orig[i] = 0


def test_parse_rk_valid_matches_original() -> None:
    text, raw_orig = _make_valid_rk()
    parsed, err = _parse_rk_input(text)
    try:
        assert err is None
        assert bytes(parsed) == bytes(raw_orig), (
            "REGRESSION: _parse_rk_input returned bytes that do not match "
            "the original raw key"
        )
    finally:
        if parsed is not None:
            for i in range(len(parsed)):
                parsed[i] = 0
        for i in range(len(raw_orig)):
            raw_orig[i] = 0


def test_parse_rk_bad_checksum_returns_none_and_error() -> None:
    text, raw_orig = _make_valid_rk()
    try:
        # Corrupt the last character of the checksum
        corrupted = text[:-1] + ("A" if text[-1] != "A" else "B")
        parsed, err = _parse_rk_input(corrupted)
        assert parsed is None, (
            "REGRESSION: bad-checksum key returned a non-None bytearray"
        )
        assert isinstance(err, str) and len(err) > 0, (
            "REGRESSION: bad-checksum key did not return a non-empty error string"
        )
    finally:
        for i in range(len(raw_orig)):
            raw_orig[i] = 0


def test_parse_rk_bad_checksum_error_mentions_typo() -> None:
    text, raw_orig = _make_valid_rk()
    try:
        corrupted = text[:-1] + ("A" if text[-1] != "A" else "B")
        _, err = _parse_rk_input(corrupted)
        assert err is not None
        assert "typo" in err.lower() or "check" in err.lower(), (
            f"REGRESSION: bad-checksum error does not say 'typo' or 'check': {err!r}"
        )
    finally:
        for i in range(len(raw_orig)):
            raw_orig[i] = 0


def test_parse_rk_empty_string_returns_error() -> None:
    parsed, err = _parse_rk_input("")
    assert parsed is None, "REGRESSION: empty string returned a bytearray"
    assert isinstance(err, str) and len(err) > 0, (
        "REGRESSION: empty string returned no error message"
    )


def test_parse_rk_garbage_returns_error() -> None:
    parsed, err = _parse_rk_input("not-a-key-at-all")
    assert parsed is None, "REGRESSION: garbage input returned a bytearray"
    assert err is not None, "REGRESSION: garbage input returned no error"


def test_parse_rk_wrong_length_returns_error() -> None:
    parsed, err = _parse_rk_input("RK1 AAAA-BBBB")
    assert parsed is None, "REGRESSION: short key returned a bytearray"
    assert err is not None, "REGRESSION: short key returned no error"


def test_parse_rk_normalises_case() -> None:
    """parse_recovery_key normalises Crockford case; _parse_rk_input must
    honour that so users who type lowercase are not rejected."""
    text, raw_orig = _make_valid_rk()
    try:
        parsed, err = _parse_rk_input(text.lower())
        assert err is None, (
            f"REGRESSION: lowercase valid key was rejected: {err!r}"
        )
        assert parsed is not None
    finally:
        if parsed is not None:
            for i in range(len(parsed)):
                parsed[i] = 0
        for i in range(len(raw_orig)):
            raw_orig[i] = 0


def test_parse_rk_normalises_without_hyphens() -> None:
    """Users may type the key without hyphens; parse_recovery_key strips them."""
    text, raw_orig = _make_valid_rk()
    try:
        no_hyphens = text.replace("-", "").replace(" ", " ")
        parsed, err = _parse_rk_input(no_hyphens)
        assert err is None, (
            f"REGRESSION: key without hyphens was rejected: {err!r}"
        )
    finally:
        if parsed is not None:
            for i in range(len(parsed)):
                parsed[i] = 0
        for i in range(len(raw_orig)):
            raw_orig[i] = 0


# ---------------------------------------------------------------------------
# _applicable_manage_actions
#
# Given a vault_info() dict, this function returns the list of action IDs
# whose buttons should appear in manage_vault_dialog.  It must hide actions
# that don't apply (e.g. upgrade_v2 on a v2 vault) and show all that do.
# ---------------------------------------------------------------------------

def test_manage_actions_v1_vault() -> None:
    info = {"format": 1, "kdf": "pbkdf2-hmac-sha256", "recovery_slot": False}
    actions = _applicable_manage_actions(info)
    assert "change_password" in actions, (
        "REGRESSION: change_password missing for v1 vault"
    )
    assert "upgrade_v2" in actions, (
        "REGRESSION: upgrade_v2 missing for v1 vault"
    )
    assert "setup_recovery" not in actions, (
        "REGRESSION: setup_recovery shown for v1 vault (not supported)"
    )
    assert "reissue_recovery" not in actions, (
        "REGRESSION: reissue_recovery shown for v1 vault"
    )


def test_manage_actions_v2_no_recovery() -> None:
    info = {"format": 2, "kdf": "scrypt", "recovery_slot": False}
    actions = _applicable_manage_actions(info)
    assert "change_password" in actions, (
        "REGRESSION: change_password missing for v2 vault without recovery slot"
    )
    assert "setup_recovery" in actions, (
        "REGRESSION: setup_recovery missing for v2 vault without recovery slot"
    )
    assert "reissue_recovery" not in actions, (
        "REGRESSION: reissue_recovery shown for v2 vault that has no recovery slot"
    )
    assert "upgrade_v2" not in actions, (
        "REGRESSION: upgrade_v2 shown for a v2 vault"
    )


def test_manage_actions_v2_with_recovery() -> None:
    info = {"format": 2, "kdf": "scrypt", "recovery_slot": True,
            "recovery_slot_id": "ABCD"}
    actions = _applicable_manage_actions(info)
    assert "change_password" in actions, (
        "REGRESSION: change_password missing for v2 vault with recovery slot"
    )
    assert "reissue_recovery" in actions, (
        "REGRESSION: reissue_recovery missing for v2 vault with recovery slot"
    )
    assert "setup_recovery" not in actions, (
        "REGRESSION: setup_recovery shown for v2 vault that already has a recovery slot"
    )
    assert "upgrade_v2" not in actions, (
        "REGRESSION: upgrade_v2 shown for a v2 vault"
    )


def test_manage_actions_error_returns_empty() -> None:
    info = {"error": "could not read vault.enc"}
    actions = _applicable_manage_actions(info)
    assert actions == [], (
        f"REGRESSION: error vault_info returned {actions!r} instead of []"
    )


def test_manage_actions_no_vault_returns_empty() -> None:
    info = {"error": "no vault"}
    actions = _applicable_manage_actions(info)
    assert actions == [], (
        "REGRESSION: 'no vault' info returned non-empty actions"
    )


def test_manage_actions_change_password_always_first() -> None:
    for info in [
        {"format": 1, "recovery_slot": False},
        {"format": 2, "recovery_slot": False},
        {"format": 2, "recovery_slot": True},
    ]:
        actions = _applicable_manage_actions(info)
        assert actions[0] == "change_password", (
            f"REGRESSION: change_password is not first in {actions!r} for {info!r}"
        )


def test_manage_actions_upgrade_v2_only_for_v1() -> None:
    """upgrade_v2 must appear for v1 and not for v2."""
    v1_info = {"format": 1, "recovery_slot": False}
    v2_info = {"format": 2, "recovery_slot": False}
    assert "upgrade_v2" in _applicable_manage_actions(v1_info)
    assert "upgrade_v2" not in _applicable_manage_actions(v2_info)


# ---------------------------------------------------------------------------
# _manage_action_result_keys
#
# Specifies the dict keys manage_vault_dialog produces for each action.
# This is the contract Lane 11 (mcp_server.py) codes against; if the keys
# change, the test fails loudly before any integration breakage reaches CI.
# ---------------------------------------------------------------------------

def test_result_keys_change_password() -> None:
    keys = _manage_action_result_keys("change_password")
    assert keys == frozenset({"action", "old_password", "new_password"}), (
        f"REGRESSION: change_password result keys are {keys!r}, "
        f"expected {{'action', 'old_password', 'new_password'}}"
    )


def test_result_keys_setup_recovery() -> None:
    keys = _manage_action_result_keys("setup_recovery")
    assert keys == frozenset({"action", "password"}), (
        f"REGRESSION: setup_recovery result keys are {keys!r}, "
        f"expected {{'action', 'password'}}"
    )


def test_result_keys_reissue_recovery() -> None:
    keys = _manage_action_result_keys("reissue_recovery")
    assert keys == frozenset({"action", "password"}), (
        f"REGRESSION: reissue_recovery result keys are {keys!r}, "
        f"expected {{'action', 'password'}}"
    )


def test_result_keys_upgrade_v2() -> None:
    keys = _manage_action_result_keys("upgrade_v2")
    assert keys == frozenset({"action", "password"}), (
        f"REGRESSION: upgrade_v2 result keys are {keys!r}, "
        f"expected {{'action', 'password'}}"
    )


def test_result_keys_all_contain_action() -> None:
    """Every result dict must contain 'action' as the discriminant."""
    for a in ("change_password", "setup_recovery", "reissue_recovery", "upgrade_v2"):
        keys = _manage_action_result_keys(a)
        assert "action" in keys, (
            f"REGRESSION: 'action' key missing from result contract for {a!r}"
        )


def test_result_keys_change_password_has_two_passwords() -> None:
    keys = _manage_action_result_keys("change_password")
    assert "old_password" in keys and "new_password" in keys, (
        "REGRESSION: change_password contract missing old_password or new_password"
    )


def test_result_keys_single_password_actions() -> None:
    for a in ("setup_recovery", "reissue_recovery", "upgrade_v2"):
        keys = _manage_action_result_keys(a)
        assert "password" in keys, (
            f"REGRESSION: {a!r} contract missing 'password' key"
        )
        assert "old_password" not in keys and "new_password" not in keys, (
            f"REGRESSION: {a!r} has old_password/new_password but should only have 'password'"
        )


# ---------------------------------------------------------------------------
# Contract integrity: applicable actions × result keys
#
# For each vault state, every action the dialog offers must have a well-
# defined result-key contract.  This cross-product check catches cases where
# an action is added to _applicable_manage_actions but forgotten in
# _manage_action_result_keys (or vice versa).
# ---------------------------------------------------------------------------

def test_all_applicable_actions_have_defined_result_keys() -> None:
    all_infos = [
        {"format": 1, "recovery_slot": False},
        {"format": 2, "recovery_slot": False},
        {"format": 2, "recovery_slot": True},
    ]
    known_actions = {"change_password", "setup_recovery", "reissue_recovery", "upgrade_v2"}
    for info in all_infos:
        for action in _applicable_manage_actions(info):
            assert action in known_actions, (
                f"REGRESSION: _applicable_manage_actions returned unknown action "
                f"{action!r} for info {info!r}"
            )
            keys = _manage_action_result_keys(action)
            assert "action" in keys, (
                f"REGRESSION: result contract for {action!r} lacks 'action' key"
            )


# ---------------------------------------------------------------------------
# Test runner
# ---------------------------------------------------------------------------

def _run(fn) -> bool:
    print(f"Running {fn.__name__} ...", flush=True)
    try:
        fn()
        print("  PASS")
        return True
    except Exception as exc:
        import traceback
        print(f"  FAIL: {exc}")
        traceback.print_exc()
        return False


if __name__ == "__main__":
    tests = [v for k, v in sorted(globals().items())
             if k.startswith("test_") and callable(v)]

    passed = [t for t in tests if _run(t)]
    failed = [t for t in tests if t not in passed]

    print()
    print(f"Results: {len(passed)}/{len(tests)} passed")
    if failed:
        print(f"FAILED: {[f.__name__ for f in failed]}")
        sys.exit(1)
    else:
        print("All tests passed.")
