"""Vault storage.

Two files hold the state, deliberately split by sensitivity:

  vault_index.json   plaintext map of  VAR_NAME -> placeholder number
                      (safe for anyone, including an AI agent, to read)

  vault.enc           Fernet-encrypted map of  VAR_NAME -> real secret value
                      (unreadable without the master password)

llm.env is regenerated purely from vault_index.json, so keeping it in
sync never requires the master password.

All writes to these files are atomic (write to a temp file in the same
directory, fsync, then os.replace over the target) so a crash or power
loss mid-write can never leave a truncated/corrupted vault.
"""
import json
import os
import re
import tempfile
from pathlib import Path

from . import crypto

ROOT = Path(__file__).resolve().parent.parent
SALT_FILE = ROOT / "vault.salt"
SECRETS_FILE = ROOT / "vault.enc"
INDEX_FILE = ROOT / "vault_index.json"
ENV_FILE = ROOT / "llm.env"

VAR_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def validate_var_name(name: str) -> str:
    if not VAR_NAME_RE.match(name):
        raise ValueError(
            f"Invalid variable name {name!r} -- must match [A-Za-z_][A-Za-z0-9_]* "
            "(letters, digits, underscore; can't start with a digit, no newlines/spaces)."
        )
    return name


def _atomic_write_bytes(path: Path, data: bytes, mode: int = 0o600) -> None:
    fd, tmp_path = tempfile.mkstemp(dir=str(path.parent), prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "wb") as f:
            f.write(data)
            f.flush()
            os.fsync(f.fileno())
        try:
            os.chmod(tmp_path, mode)
        except OSError:
            pass  # best-effort; Windows ACLs don't map cleanly onto POSIX modes
        os.replace(tmp_path, path)
    except BaseException:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def _atomic_write_text(path: Path, text: str, mode: int = 0o644) -> None:
    _atomic_write_bytes(path, text.encode("utf-8"), mode=mode)


def vault_exists() -> bool:
    return SALT_FILE.exists() and SECRETS_FILE.exists()


def load_index() -> dict:
    if not INDEX_FILE.exists():
        return {}
    try:
        data = json.loads(INDEX_FILE.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise ValueError(f"vault_index.json is corrupted: {e}") from None
    if not isinstance(data, dict):
        raise ValueError("vault_index.json must contain a JSON object of VAR_NAME -> number.")
    return data


def save_index(index: dict) -> None:
    for name in index:
        validate_var_name(name)
    _atomic_write_text(INDEX_FILE, json.dumps(index, indent=2, sort_keys=True) + "\n")
    regenerate_llm_env(index)


def next_placeholder(index: dict) -> int:
    used = set(index.values())
    n = 1
    while n in used:
        n += 1
    return n


def regenerate_llm_env(index: dict) -> None:
    lines = [
        "# AUTO-GENERATED by llm-env-vault -- do not hand-edit.",
        "# Real values live encrypted in vault.enc and are never written here.",
        "# Run `python run_with_env.py -- <command>` to execute your app with the real values.",
        "",
    ]
    for var_name, placeholder in sorted(index.items(), key=lambda kv: kv[1]):
        validate_var_name(var_name)
        lines.append(f'{var_name}="value {placeholder}"')
    _atomic_write_text(ENV_FILE, "\n".join(lines) + "\n")


def create_secrets_vault(password: str) -> None:
    """First-time setup: new salt, empty encrypted secrets store.

    Refuses if vault.salt already exists without a matching vault.enc --
    generating a fresh salt in that state would silently make any
    surviving backup copy of vault.enc permanently undecryptable, even
    with the correct password.
    """
    if SALT_FILE.exists():
        raise RuntimeError(
            "vault.salt already exists but vault.enc is missing. Refusing to "
            "generate a new salt -- restore vault.enc from backup, or delete "
            "vault.salt yourself if you really want to start over."
        )
    salt = crypto.new_salt()
    _atomic_write_bytes(SALT_FILE, salt)
    save_secrets(password, {})


def load_secrets(password: str) -> dict:
    salt = SALT_FILE.read_bytes()
    token = SECRETS_FILE.read_bytes()
    plaintext = crypto.decrypt(password, salt, token)
    try:
        return json.loads(plaintext.decode("utf-8"))
    except json.JSONDecodeError:
        raise ValueError("Decrypted vault contents are corrupted.") from None


def save_secrets(password: str, secrets: dict) -> None:
    salt = SALT_FILE.read_bytes()
    token = crypto.encrypt(password, salt, json.dumps(secrets).encode("utf-8"))
    _atomic_write_bytes(SECRETS_FILE, token)
